version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistema_venta
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
    image: sistemav2:latest
    ports:
      - 4000:4000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/sistema_venta
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql-data:
